# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Open Angel Arena
email: chrisinajar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official website for Open Angel Arena, check your MMR and probably other things.
baseurl: "/oaa.gg" # the subpath of your site, e.g. /blog
url: "https://openangelarena.github.io/" # the base hostname & protocol for your site
twitter_username: chrisinajar
github_username:  chrisinajar

exclude: [vendor, node_modules]

# Build settings
markdown: kramdown

# set up authors and /team/ pages
collections:
  authors:
    output: true

sass:
  style: :compressed

compress_html:
  clippings: all

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

# Prose configuration
prose:
  rooturl: "pages"
  siteurl: "https://openangelarena.github.io/oaa.gg/"
  ignore:
    - webAppManifest.html
    - leaderboard.html
    - /_includes
    - /_layouts
  media: 'uploads'
